### ISSUE TITLE
handle MSG_UPDATE_DATA and MSG_UPDATE_CARD in ocgcore instead of in server code

### ISSUE THREAD

**Issue by DailyShana** [Fluorohydride/ygopro-core#300]
Currently `MSG_UPDATE_DATA` or `MSG_UPDATE_CARD` is sent in server code, after calling ocgapi `query_field_card` and `query_card` respectively. As a part of the protocol, it's reasonable to handle this in a unified way, like other `MSG`s. And the timing of sending these msg can be controlled in a finer way.

Although server code needs update, there is no incompatibility to the client code.

idea from https://github.com/Fluorohydride/ygopro-core/tree/ygopro2

**Comment by DyXel** [comment]
I will start by saying that both are completely unused in the core even though they are defined in `common.h`  (there are actually plenty of them that are unused, `MSG_WAITING` being another good example), the reason might be related to the fact that at the start the client and core were the same entity (this is no longer true, and for a good reason). It doesn't make much sense to have these inside the core because they dont relate to what the core currently returns as message buffer. They are _optional_ data: In order to keep the interpreter state's (client message parsing) integrity, that data is unnecessary, it merely is additional information that is shown and interacted upon by the end user (so is `MSG_WAITING` & co).
