### ISSUE TITLE
Recent OCGCore changes

### ISSUE THREAD

**Issue by SuperAndroid17** [Fluorohydride/ygopro-core#62]
Good evening, 
I am SuperAndroid17, owner of YGOPro DevPro, I would like to inquire about a recent update to OCGCore. The core has been causing frequent crashes to our server for the past month. With plenty of out of memory exceptions, we are to believe that these errors happened from this [commit](https://github.com/Fluorohydride/ygopro-core/commit/2980ab6a5a4c892a8a6e1bc192f2332043e24061) and on. As a result, our server has become very unstable and it’s frustrating to our users. If needed, I have numerous screenshots of the errors that occur should you like to see them.

Thank you for your time.

**Comment by salix5** [comment]
Sorry for my late reply...
I believed that using void* to store pointers is a better way since size of pointer may be bigger than ptr=long.
I have checked this section several times, but I can't find the problems.
Do you have any idea about what is wrong in this section?

@mercury233 
Do you have any idea about what is wrong in this section?
Does this cause memory exceptions on your server?

**Comment by mercury233** [comment]
I don't know, and my server have no problem about this change.

**Comment by Zayelion** [comment]
The Salvation server generates a similar error. It stopped after switching to YGOSharp's latest from @Buttys.

**Comment by SuperAndroid17** [comment]
We found the cause for the issue. Sorry for the late reply, kinda forgot the issue was opened.
